project:
  type: website
  resources:
    - CNAME
  output-dir: docs

execute:
  freeze: auto

website:
  title: "mBLA: Model-Based Learning Analytics"
  navbar:
    background: info
    right:
      - href: people.qmd
        text: People
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: resources.qmd
        text: Resources
      - href: contact.qmd
        text: Contact
  page-footer: "Copyright 2024 &copy; Center of Education Technology"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
